services:
  chainlink:
    image: smartcontract/chainlink:2.25.0
    ports:
      - "6688:6688"   # HTTP (Dashboard/API)
      - "6689:6689"   # HTTPS (native TLS)
    env_file:
      - cl-node.env
    volumes:
      - ./config:/chainlink/config
      - ./config/certs:/chainlink/certs # TLS Certs
      - chainlink_data:/chainlink
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - chainlink-net
    command:
      - "node"
      - "-config"
      - "/chainlink/config/chainlink-config.toml"
      - "-secrets"
      - "/chainlink/config/cl-node.env"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6688/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:13
    env_file:
      - cl-node.env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chainlink-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  chainlink-net:
    - driver: bridge

volumes:
  chainlink_data:
  postgres_data: